<?php

namespace Atc\AlertBundle\Entity;

use DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * AlertRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @return mixed
 */
class AlertRepository extends EntityRepository
{
    public function findPending()
    {
        return $this->createQueryBuilder('a')
            ->where('a.sent = :sent')
            ->andWhere('a.date < :now')
            ->setParameter('sent', false)
            ->setParameter('now', new DateTime())
            ->getQuery()->getResult();
    }
}
